# Minimum viable alerting.
#
# Before this, the only way anyone learned the API was down was by loading the
# site. Three alarms cover the three ways this stack fails in practice: the app
# throws, the tasks won't stay up, or the database fills. Each one is a page
# worth answering — anything quieter belongs on a dashboard, not in an inbox.
#
# Email subscriptions must be confirmed by clicking the link AWS sends; until
# then the subscription is "pending confirmation" and delivers nothing.

variable "alert_email" {
  description = "Address that receives alarm notifications. Empty disables alerting entirely (no topic, no alarms)."
  type        = string
  default     = ""
}

locals {
  alerting = var.alert_email != ""
}

resource "aws_sns_topic" "alerts" {
  count = local.alerting ? 1 : 0
  name  = "${var.project}-alerts"
}

resource "aws_sns_topic_subscription" "alerts_email" {
  count     = local.alerting ? 1 : 0
  topic_arn = aws_sns_topic.alerts[0].arn
  protocol  = "email"
  endpoint  = var.alert_email
}

# 1. The app is throwing. Counts only 5xx generated by our own targets, not the
#    ALB's own 5xx (which would also fire when there are simply no healthy
#    targets — that is what alarm 2 is for, and one cause should page once).
resource "aws_cloudwatch_metric_alarm" "api_5xx" {
  count               = local.alerting ? 1 : 0
  alarm_name          = "${var.project}-api-5xx"
  alarm_description   = "The API is returning server errors. Check the request ids in /ecs/${var.project}-api."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = 300
  evaluation_periods  = 1
  threshold           = 5
  comparison_operator = "GreaterThanThreshold"
  # No data means no traffic, not a healthy service — don't cry wolf overnight.
  treat_missing_data = "notBreaching"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
    TargetGroup  = aws_lb_target_group.api.arn_suffix
  }

  alarm_actions = [aws_sns_topic.alerts[0].arn]
  ok_actions    = [aws_sns_topic.alerts[0].arn]
}

# 2. Tasks are failing their health check. Now that /health probes the database,
#    this also catches a task that boots but cannot reach RDS — the case the old
#    static {ok:true} made invisible.
resource "aws_cloudwatch_metric_alarm" "api_unhealthy_tasks" {
  count             = local.alerting ? 1 : 0
  alarm_name        = "${var.project}-api-unhealthy-tasks"
  alarm_description = "API tasks are failing their health check — either the app is broken or it cannot reach the database."
  namespace         = "AWS/ApplicationELB"
  metric_name       = "UnHealthyHostCount"
  statistic         = "Maximum"
  period            = 60
  # Two periods, so a rolling deployment's brief drain doesn't page anyone.
  evaluation_periods  = 2
  threshold           = 0
  comparison_operator = "GreaterThanThreshold"
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
    TargetGroup  = aws_lb_target_group.api.arn_suffix
  }

  alarm_actions = [aws_sns_topic.alerts[0].arn]
  ok_actions    = [aws_sns_topic.alerts[0].arn]
}

# 3. The database is filling up. A full RDS volume takes writes offline, and the
#    fix (grow storage) has a cooldown that makes it useless as an emergency
#    lever — this needs to fire with room to act. 20% of allocated storage.
resource "aws_cloudwatch_metric_alarm" "rds_storage" {
  count               = local.alerting ? 1 : 0
  alarm_name          = "${var.project}-rds-free-storage"
  alarm_description   = "RDS free storage is below 20%. Growing storage is rate-limited, so act now rather than at 0."
  namespace           = "AWS/RDS"
  metric_name         = "FreeStorageSpace"
  statistic           = "Minimum"
  period              = 300
  evaluation_periods  = 1
  threshold           = var.db_allocated_storage * 1024 * 1024 * 1024 * 0.2
  comparison_operator = "LessThanThreshold"
  # Missing data here means the instance stopped reporting — worth knowing.
  treat_missing_data = "breaching"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.main.identifier
  }

  alarm_actions = [aws_sns_topic.alerts[0].arn]
  ok_actions    = [aws_sns_topic.alerts[0].arn]
}
