-- Seed the 50 states plus DC into service_areas, all `notify` ("not in your
-- state yet, tell me when"): nothing is open until an admin opens it on
-- /admin/onboarding/service-areas. The flow reads this through the derived
-- `state_status` trait; pharmacy and shipping will read the same table later.
-- Idempotent: statuses an admin has already changed are left alone.
INSERT INTO "service_areas" ("state_code", "status", "note")
VALUES
  ('AL', 'notify', 'Alabama'),
  ('AK', 'notify', 'Alaska'),
  ('AZ', 'notify', 'Arizona'),
  ('AR', 'notify', 'Arkansas'),
  ('CA', 'notify', 'California'),
  ('CO', 'notify', 'Colorado'),
  ('CT', 'notify', 'Connecticut'),
  ('DE', 'notify', 'Delaware'),
  ('DC', 'notify', 'District of Columbia'),
  ('FL', 'notify', 'Florida'),
  ('GA', 'notify', 'Georgia'),
  ('HI', 'notify', 'Hawaii'),
  ('ID', 'notify', 'Idaho'),
  ('IL', 'notify', 'Illinois'),
  ('IN', 'notify', 'Indiana'),
  ('IA', 'notify', 'Iowa'),
  ('KS', 'notify', 'Kansas'),
  ('KY', 'notify', 'Kentucky'),
  ('LA', 'notify', 'Louisiana'),
  ('ME', 'notify', 'Maine'),
  ('MD', 'notify', 'Maryland'),
  ('MA', 'notify', 'Massachusetts'),
  ('MI', 'notify', 'Michigan'),
  ('MN', 'notify', 'Minnesota'),
  ('MS', 'notify', 'Mississippi'),
  ('MO', 'notify', 'Missouri'),
  ('MT', 'notify', 'Montana'),
  ('NE', 'notify', 'Nebraska'),
  ('NV', 'notify', 'Nevada'),
  ('NH', 'notify', 'New Hampshire'),
  ('NJ', 'notify', 'New Jersey'),
  ('NM', 'notify', 'New Mexico'),
  ('NY', 'notify', 'New York'),
  ('NC', 'notify', 'North Carolina'),
  ('ND', 'notify', 'North Dakota'),
  ('OH', 'notify', 'Ohio'),
  ('OK', 'notify', 'Oklahoma'),
  ('OR', 'notify', 'Oregon'),
  ('PA', 'notify', 'Pennsylvania'),
  ('RI', 'notify', 'Rhode Island'),
  ('SC', 'notify', 'South Carolina'),
  ('SD', 'notify', 'South Dakota'),
  ('TN', 'notify', 'Tennessee'),
  ('TX', 'notify', 'Texas'),
  ('UT', 'notify', 'Utah'),
  ('VT', 'notify', 'Vermont'),
  ('VA', 'notify', 'Virginia'),
  ('WA', 'notify', 'Washington'),
  ('WV', 'notify', 'West Virginia'),
  ('WI', 'notify', 'Wisconsin'),
  ('WY', 'notify', 'Wyoming')
ON CONFLICT ("state_code") DO NOTHING;
